FROM python:3

RUN mkdir /app

ENV TABLE=students

ENV COLUMNS=first_name,last_name

WORKDIR app

COPY . app 

RUN pip install -r app/requirements.txt

LABEL Grupo=Uno

EXPOSE 8081

ENTRYPOINT [ "python", "app/app.py" ]